### ISSUE TITLE
real ur5 does not move using moveit_planning_execution.launch

### ISSUE THREAD

**Issue by IndustrialEngStudent** [ros-industrial/ur_modern_driver#312] opened 2019-06-05 14:13 UTC
Hi,

I am trying to move the ur5 + Robotiq gripper in a small circle.
First I bring up the ur5 + robotiq gripper:

```
 roslaunch ur_modern_driver ur5_robotiq_2f85_bringup2.launch robot_ip:=192.168.1.151  [reverse_port:=REVERSE_PORT]
... logging to /home/laurah/.ros/log/2b623334-878e-11e9-92dc-8086f2694d08/roslaunch-laurah-HP-EliteBook-840-G1-17016.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://laurah-HP-EliteBook-840-G1:44949/

SUMMARY
========

PARAMETERS
 * /force_torque_sensor_controller/publish_rate: 125
 * /force_torque_sensor_controller/type: force_torque_sens...
 * /gripper/hardware_control_loop/loop_hz: 125
 * /gripper/hardware_interface/joints: ['gripper_finger1...
 * /gripper/joint_position_controller/action_monitor_rate: 10
 * /gripper/joint_position_controller/constraints/goal_time: 0.6
 * /gripper/joint_position_controller/constraints/simple_gripper_robotiq_85_left_knuckle_joint/goal: 0.01
 * /gripper/joint_position_controller/constraints/simple_gripper_robotiq_85_left_knuckle_joint/trajectory: 0.1
 * /gripper/joint_position_controller/constraints/stopped_velocity_tolerance: 0.05
 * /gripper/joint_position_controller/joint: gripper_finger1_j...
 * /gripper/joint_position_controller/state_publish_rate: 125
 * /gripper/joint_position_controller/stop_trajectory_duration: 0.5
 * /gripper/joint_position_controller/type: position_controll...
 * /gripper/joint_state_controller/publish_rate: 125
 * /gripper/joint_state_controller/type: joint_state_contr...
 * /gripper/joint_trajectory_controller/joint: ['gripper_finger1...
 * /gripper/joint_trajectory_controller/type: position_controll...
 * /hardware_control_loop/loop_hz: 125
 * /hardware_interface/joints: ['shoulder_pan_jo...
 * /joint_group_vel_controller/joints: ['shoulder_pan_jo...
 * /joint_group_vel_controller/type: velocity_controll...
 * /joint_state_controller/publish_rate: 125
 * /joint_state_controller/type: joint_state_contr...
 * /pos_based_pos_traj_controller/action_monitor_rate: 10
 * /pos_based_pos_traj_controller/constraints/elbow_joint/goal: 0.1
 * /pos_based_pos_traj_controller/constraints/elbow_joint/trajectory: 0.1
 * /pos_based_pos_traj_controller/constraints/goal_time: 0.6
 * /pos_based_pos_traj_controller/constraints/shoulder_lift_joint/goal: 0.1
 * /pos_based_pos_traj_controller/constraints/shoulder_lift_joint/trajectory: 0.1
 * /pos_based_pos_traj_controller/constraints/shoulder_pan_joint/goal: 0.1
 * /pos_based_pos_traj_controller/constraints/shoulder_pan_joint/trajectory: 0.1
 * /pos_based_pos_traj_controller/constraints/stopped_velocity_tolerance: 0.05
 * /pos_based_pos_traj_controller/constraints/wrist_1_joint/goal: 0.1
 * /pos_based_pos_traj_controller/constraints/wrist_1_joint/trajectory: 0.1
 * /pos_based_pos_traj_controller/constraints/wrist_2_joint/goal: 0.1
 * /pos_based_pos_traj_controller/constraints/wrist_2_joint/trajectory: 0.1
 * /pos_based_pos_traj_controller/constraints/wrist_3_joint/goal: 0.1
 * /pos_based_pos_traj_controller/constraints/wrist_3_joint/trajectory: 0.1
 * /pos_based_pos_traj_controller/joints: ['shoulder_pan_jo...
 * /pos_based_pos_traj_controller/state_publish_rate: 125
 * /pos_based_pos_traj_controller/stop_trajectory_duration: 0.5
 * /pos_based_pos_traj_controller/type: position_controll...
 * /robot_description: <?xml version="1....
 * /robotiq_85_driver/baud: 115200
 * /robotiq_85_driver/comport: /dev/ttyUSB0
 * /robotiq_85_driver/num_grippers: 1
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /ur_driver/base_frame: base
 * /ur_driver/max_joint_difference: 0.01
 * /ur_driver/max_payload: 5.0
 * /ur_driver/max_velocity: 10.0
 * /ur_driver/max_waiting_time: 2.0
 * /ur_driver/min_payload: 0.0
 * /ur_driver/prefix: 
 * /ur_driver/require_activation: Never
 * /ur_driver/reverse_ip_address: 
 * /ur_driver/reverse_port: 50001
 * /ur_driver/robot_ip_address: 192.168.1.151
 * /ur_driver/servoj_gain: 100.0
 * /ur_driver/servoj_lookahead_time: 1.0
 * /ur_driver/servoj_time: 0.008
 * /ur_driver/servoj_time_waiting: 0.001
 * /ur_driver/shutdown_on_disconnect: True
 * /ur_driver/time_interval: 0.008
 * /ur_driver/tool_frame: tool0_controller
 * /ur_driver/use_lowbandwidth_trajectory_follower: False
 * /ur_driver/use_ros_control: False
 * /vel_based_pos_traj_controller/action_monitor_rate: 10
 * /vel_based_pos_traj_controller/constraints/elbow_joint/goal: 0.1
 * /vel_based_pos_traj_controller/constraints/elbow_joint/trajectory: 0.1
 * /vel_based_pos_traj_controller/constraints/goal_time: 0.6
 * /vel_based_pos_traj_controller/constraints/shoulder_lift_joint/goal: 0.1
 * /vel_based_pos_traj_controller/constraints/shoulder_lift_joint/trajectory: 0.1
 * /vel_based_pos_traj_controller/constraints/shoulder_pan_joint/goal: 0.1
 * /vel_based_pos_traj_controller/constraints/shoulder_pan_joint/trajectory: 0.1
 * /vel_based_pos_traj_controller/constraints/stopped_velocity_tolerance: 0.05
 * /vel_based_pos_traj_controller/constraints/wrist_1_joint/goal: 0.1
 * /vel_based_pos_traj_controller/constraints/wrist_1_joint/trajectory: 0.1
 * /vel_based_pos_traj_controller/constraints/wrist_2_joint/goal: 0.1
 * /vel_based_pos_traj_controller/constraints/wrist_2_joint/trajectory: 0.1
 * /vel_based_pos_traj_controller/constraints/wrist_3_joint/goal: 0.1
 * /vel_based_pos_traj_controller/constraints/wrist_3_joint/trajectory: 0.1
 * /vel_based_pos_traj_controller/gains/elbow_joint/d: 0.1
 * /vel_based_pos_traj_controller/gains/elbow_joint/i: 0.01
 * /vel_based_pos_traj_controller/gains/elbow_joint/i_clamp: 1
 * /vel_based_pos_traj_controller/gains/elbow_joint/p: 1.2
 * /vel_based_pos_traj_controller/gains/shoulder_lift_joint/d: 0.1
 * /vel_based_pos_traj_controller/gains/shoulder_lift_joint/i: 0.01
 * /vel_based_pos_traj_controller/gains/shoulder_lift_joint/i_clamp: 1
 * /vel_based_pos_traj_controller/gains/shoulder_lift_joint/p: 1.2
 * /vel_based_pos_traj_controller/gains/shoulder_pan_joint/d: 0.1
 * /vel_based_pos_traj_controller/gains/shoulder_pan_joint/i: 0.01
 * /vel_based_pos_traj_controller/gains/shoulder_pan_joint/i_clamp: 1
 * /vel_based_pos_traj_controller/gains/shoulder_pan_joint/p: 1.2
 * /vel_based_pos_traj_controller/gains/wrist_1_joint/d: 0.1
 * /vel_based_pos_traj_controller/gains/wrist_1_joint/i: 0.01
 * /vel_based_pos_traj_controller/gains/wrist_1_joint/i_clamp: 1
 * /vel_based_pos_traj_controller/gains/wrist_1_joint/p: 1.2
 * /vel_based_pos_traj_controller/gains/wrist_2_joint/d: 0.1
 * /vel_based_pos_traj_controller/gains/wrist_2_joint/i: 0.01
 * /vel_based_pos_traj_controller/gains/wrist_2_joint/i_clamp: 1
 * /vel_based_pos_traj_controller/gains/wrist_2_joint/p: 1.2
 * /vel_based_pos_traj_controller/gains/wrist_3_joint/d: 0.1
 * /vel_based_pos_traj_controller/gains/wrist_3_joint/i: 0.01
 * /vel_based_pos_traj_controller/gains/wrist_3_joint/i_clamp: 1
 * /vel_based_pos_traj_controller/gains/wrist_3_joint/p: 1.2
 * /vel_based_pos_traj_controller/joints: ['shoulder_pan_jo...
 * /vel_based_pos_traj_controller/state_publish_rate: 125
 * /vel_based_pos_traj_controller/stop_trajectory_duration: 0.5
 * /vel_based_pos_traj_controller/type: velocity_controll...
 * /vel_based_pos_traj_controller/velocity_ff/elbow_joint: 1.0
 * /vel_based_pos_traj_controller/velocity_ff/shoulder_lift_joint: 1.0
 * /vel_based_pos_traj_controller/velocity_ff/shoulder_pan_joint: 1.0
 * /vel_based_pos_traj_controller/velocity_ff/wrist_1_joint: 1.0
 * /vel_based_pos_traj_controller/velocity_ff/wrist_2_joint: 1.0
 * /vel_based_pos_traj_controller/velocity_ff/wrist_3_joint: 1.0

NODES
  /
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    robotiq_85_driver (robotiq_85_driver/robotiq_85_driver)
    ros_control_controller_manager (controller_manager/controller_manager)
    ur_driver (ur_modern_driver/ur_driver)

ROS_MASTER_URI=http://localhost:11311

process[robot_state_publisher-1]: started with pid [17036]
process[ur_driver-2]: started with pid [17037]
process[ros_control_controller_manager-3]: started with pid [17039]
process[robotiq_85_driver-4]: started with pid [17050]
[ INFO] [1559742970.192088197]: Setting up connection: 192.168.1.151:30003
[ INFO] [1559742970.193715953]: Connection established for 192.168.1.151:30003
[ INFO] [1559742970.193776817]: Setting up connection: 192.168.1.151:30001
[ INFO] [1559742970.195066480]: Connection established for 192.168.1.151:30001
[ INFO] [1559742970.197062827]: Got VersionMessage:
[ INFO] [1559742970.197100808]: project name: URControl
[ INFO] [1559742970.197116727]: version: 3.9.0
[ INFO] [1559742970.197130296]: build date: 21-02-2019, 15:09:20
[ INFO] [1559742970.197143184]: Disconnecting from 192.168.1.151:30001
[ INFO] [1559742970.210343228]: ActionServer enabled
[ INFO] [1559742970.210560169]: Use standard trajectory follower
[ INFO] [1559742970.213257125]: Setting up connection: :50001
[ INFO] [1559742970.213460507]: Connection established for :50001
[ INFO] [1559742970.213576251]: Initializing ur_driver/URScript subscriber
[ INFO] [1559742970.218433727]: The ur_driver/URScript initialized
[ INFO] [1559742970.218482071]: Notifier: Pipeline disconnect will shutdown the node
[ INFO] [1559742970.238703477]: Service 'ur_driver/robot_enable' activation mode: Never
[ INFO] [1559742970.238764606]: Starting main loop
[ INFO] [1559742970.238990497]: Setting up connection: 192.168.1.151:30003
[ INFO] [1559742970.239082006]: Starting pipeline RTPacket
[ INFO] [1559742970.239216833]: Setting up connection: 192.168.1.151:30002
[ INFO] [1559742970.239299913]: Starting pipeline StatePacket
[ INFO] [1559742970.240570777]: Connection established for 192.168.1.151:30003
[ INFO] [1559742970.240864038]: Connection established for 192.168.1.151:30002
[ INFO] [1559742970.242381435]: Starting ActionServer
[ INFO] [1559742970.242544963]: Trajectory thread started
```
Then: `roslaunch lau_moveit_config ur5_robotiq_2f85_moveit_planning_execution.launch`
which give me no trouble execpt two warnings:
[ WARN] [1559742315.209671241]: Skipping virtual joint 'virtual_joint' because its child frame 'base_link' does not match the URDF frame 'world'
...
`[ WARN] [1559742489.710331295]: The complete state of the robot is not yet known.  Missing gripper_finger1_joint`

Then: `roslaunch lau_moveit_config moveit_rviz.launch config:=true`, which is also not a problem.

Then, I run the script using the move group python interface: " rosrun ur5_notebook motionplanner1LauCircle_gripper.py"

In rviz I see the robot moving as desired. The starting position is the exact position as the real robot is. Thus, I think the connection is working since rviz shows the real state of the robot. However, the real ur5 does not move. 

How can I fix this?

**Comment by miguelprada** [comment] 2019-06-05 14:48
It's impossible for us to help you with this, since we have no idea of what are the contents of `ur5_robotiq_2f85_bringup2.launch` or anything in `lau_moveit_config` or `ur5_notebook` packages. You need to be much more specific to ask for help.

Since this doesn't seem to be a problem related to this driver, but rather to your application configuration, I will close this issue. Feel free to keep commenting or ask in [ROS Answers](https://answers.ros.org/questions/) if you have general questions about configuring a ROS-based application.

**Closed by miguelprada** 2019-06-05 14:48 UTC

**Comment by gavanderhoorn** [comment] 2019-06-05 15:06
I would agree with @miguelprada that this issue seems a bit too localised for us to address here: we don't know how you configured things, nor does `ur_modern_driver` have anything to do with robotiq grippers.

However, if you can reproduce your problem with *just* the files from this repository, then we can try to see whether we can resolve it.

**Comment by nag92** [comment] 2019-07-08 15:28
I am have the same issue with just the vanilla ur_modern_driver and ur_robot packages

**Comment by gavanderhoorn** [comment] 2019-07-08 16:25
Please do not comment on closed issues.

Open a new one. If it's really the same issue, we'll close the new one as a duplicate and re-open this one.
