### ISSUE TITLE
Pipeline overflow - ROS control ur5

### ISSUE THREAD

**Issue by runeg96** [ros-industrial/ur_modern_driver#207] opened 2018-10-04 09:00 UTC
When using ros_control for the ur5 with the following command roslaunch ur_modern_driver ur5_ros_control.launch robot_ip:='robot ip'. An issue happen where the robot starts moving/vibrating while given the error "Pipeline producer overflowed! <RTPacket>" in the terminal. I don't know what is causing this problem.

This is tried on the ur firmware 3.5.4.10845 (Apr 13 2018), with ros-kinetic
A screenshot of the terminal:

![pczguxq](https://user-images.githubusercontent.com/4550046/46463987-93fb3a00-c7c5-11e8-8134-95e3f3d417e6.png)

**Comment by gavanderhoorn** [comment] 2018-10-04 09:07
I think this is a duplicate of https://github.com/Zagitta/ur_modern_driver/issues/14?

Not that that was resolved, but just making sure we keep things linked.

**Comment by runeg96** [comment] 2018-10-04 10:57
We can confirm by switching the controller from "vel_based_pos_traj_controller" to pos_based_pos_traj_controller" the pipeline overflow stops, and the robot can be moved through moveit

**Comment by gavanderhoorn** [comment] 2018-10-05 06:48
Ok. Also not a solution, but at least a work-around.

**Comment by Obbart** [comment] 2019-02-21 13:20
Hi, I have the same problem described above but with the  `ur10_ros_control.launch` and `pos_based_pos_traj_controller`.
The robot can be moved for a certain ammount of time even if the error appears, then either it stops either the motion becomes jerky. 
In my application the coordinates are sent to the controller from the `jog_arm` package but the overflow occours even if the `jog_arm_server` is not running

**Comment by danielkruse** [comment] 2019-06-17 23:30
Hi I'm receiving the same output when attempting to run the ros-control velocity controller.  I am seeing the spew of "Pipeline producer overflowed!" output on the terminal.

On the teach pendant (UR5 running polyscope 3.0.xx) I am getting a popup message "Type error: speedj takes exactly 3 arguments (2 given)" and will frequently cause the robot to Fault.

Has there been any work on this / is this the current recommended method for real time control of the robot through ur modern driver?

**Comment by gavanderhoorn** [comment] 2019-06-18 10:52
> UR5 running polyscope 3.0.xx

Due to inactivity this was not resolved I believe, but versions 3.0 of the system software have been problematic in the past.

Would you have the possibility of upgrading to at least 3.2?

**Comment by ThomHordijk** [comment] 2019-06-18 13:05
Hi we are experiencing the same error however for us it happens when we press the emergency stop while the arm is executing its path. It is not possible to recover without turning off the entire program. 
Is it possible to terminate the path being executed? Or would the issue be caused by something else?

**Comment by danielkruse** [comment] 2019-06-18 16:09
> > UR5 running polyscope 3.0.xx
> 
> Due to inactivity this was not resolved I believe, but versions 3.0 of the system software have been problematic in the past.
> 
> Would you have the possibility of upgrading to at least 3.2?

I will upgrade to the most recent 3.2.xxx and get back to you.  I guess the arm hadn't received an update since 2014...

**Comment by danielkruse** [comment] 2019-06-18 20:33
I updated to 3.2.xx, but ran into [136](https://github.com/ros-industrial/ur_modern_driver/issues/136) so I went ahead and updated to 3.5.xx as the recommended Polyscope target from that thread, but I'm still seeing the "Pipeline producer overflowed!" message when running the ros-control launch.  

I seem to be able to actually pass commands to the robot controller now without crashing the robot firmware, but the commands are extremely delayed (on the order of seconds).

**Comment by gavanderhoorn** [comment] 2019-06-18 20:42
This is probably going to need some proper debugging.

Can you start by copy-pasting a verbatim example of the error? There should be a pipeline name mentioned in the error message. Is it also `RTPacket`?

**Comment by danielkruse** [comment] 2019-06-18 21:18
This is the full verbose output of roslaunch.  The "Pipeline producer overflowed" message started about 5-10 seconds after launch.

`roslaunch ur_modern_driver ur5_ros_control.launch robot_ip:=192.168.3.100`

> started roslaunch server http://localadmin-Precision-5820-Tower:42457/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /force_torque_sensor_controller/publish_rate: 125
>  * /force_torque_sensor_controller/type: force_torque_sens...
>  * /hardware_control_loop/loop_hz: 125
>  * /hardware_interface/joints: ['shoulder_pan_jo...
>  * /joint_group_vel_controller/joints: ['shoulder_pan_jo...
>  * /joint_group_vel_controller/type: velocity_controll...
>  * /joint_state_controller/publish_rate: 125
>  * /joint_state_controller/type: joint_state_contr...
>  * /pos_based_pos_traj_controller/action_monitor_rate: 10
>  * /pos_based_pos_traj_controller/constraints/elbow_joint/goal: 0.1
>  * /pos_based_pos_traj_controller/constraints/elbow_joint/trajectory: 0.1
>  * /pos_based_pos_traj_controller/constraints/goal_time: 0.6
>  * /pos_based_pos_traj_controller/constraints/shoulder_lift_joint/goal: 0.1
>  * /pos_based_pos_traj_controller/constraints/shoulder_lift_joint/trajectory: 0.1
>  * /pos_based_pos_traj_controller/constraints/shoulder_pan_joint/goal: 0.1
>  * /pos_based_pos_traj_controller/constraints/shoulder_pan_joint/trajectory: 0.1
>  * /pos_based_pos_traj_controller/constraints/stopped_velocity_tolerance: 0.05
>  * /pos_based_pos_traj_controller/constraints/wrist_1_joint/goal: 0.1
>  * /pos_based_pos_traj_controller/constraints/wrist_1_joint/trajectory: 0.1
>  * /pos_based_pos_traj_controller/constraints/wrist_2_joint/goal: 0.1
>  * /pos_based_pos_traj_controller/constraints/wrist_2_joint/trajectory: 0.1
>  * /pos_based_pos_traj_controller/constraints/wrist_3_joint/goal: 0.1
>  * /pos_based_pos_traj_controller/constraints/wrist_3_joint/trajectory: 0.1
>  * /pos_based_pos_traj_controller/joints: ['shoulder_pan_jo...
>  * /pos_based_pos_traj_controller/state_publish_rate: 125
>  * /pos_based_pos_traj_controller/stop_trajectory_duration: 0.5
>  * /pos_based_pos_traj_controller/type: position_controll...
>  * /robot_description: <?xml version="1....
>  * /rosdistro: kinetic
>  * /rosversion: 1.12.14
>  * /ur_hardware_interface/base_frame: base
>  * /ur_hardware_interface/max_payload: 3.0
>  * /ur_hardware_interface/max_velocity: 10.0
>  * /ur_hardware_interface/min_payload: 0.0
>  * /ur_hardware_interface/prefix: 
>  * /ur_hardware_interface/reverse_ip_address: 
>  * /ur_hardware_interface/reverse_port: 50001
>  * /ur_hardware_interface/robot_ip_address: 192.168.3.100
>  * /ur_hardware_interface/servoj_gain: 750.0
>  * /ur_hardware_interface/shutdown_on_disconnect: True
>  * /ur_hardware_interface/tool_frame: tool0_controller
>  * /ur_hardware_interface/use_ros_control: True
>  * /vel_based_pos_traj_controller/action_monitor_rate: 10
>  * /vel_based_pos_traj_controller/constraints/elbow_joint/goal: 0.1
>  * /vel_based_pos_traj_controller/constraints/elbow_joint/trajectory: 0.1
>  * /vel_based_pos_traj_controller/constraints/goal_time: 0.6
>  * /vel_based_pos_traj_controller/constraints/shoulder_lift_joint/goal: 0.1
>  * /vel_based_pos_traj_controller/constraints/shoulder_lift_joint/trajectory: 0.1
>  * /vel_based_pos_traj_controller/constraints/shoulder_pan_joint/goal: 0.1
>  * /vel_based_pos_traj_controller/constraints/shoulder_pan_joint/trajectory: 0.1
>  * /vel_based_pos_traj_controller/constraints/stopped_velocity_tolerance: 0.05
>  * /vel_based_pos_traj_controller/constraints/wrist_1_joint/goal: 0.1
>  * /vel_based_pos_traj_controller/constraints/wrist_1_joint/trajectory: 0.1
>  * /vel_based_pos_traj_controller/constraints/wrist_2_joint/goal: 0.1
>  * /vel_based_pos_traj_controller/constraints/wrist_2_joint/trajectory: 0.1
>  * /vel_based_pos_traj_controller/constraints/wrist_3_joint/goal: 0.1
>  * /vel_based_pos_traj_controller/constraints/wrist_3_joint/trajectory: 0.1
>  * /vel_based_pos_traj_controller/gains/elbow_joint/d: 0.1
>  * /vel_based_pos_traj_controller/gains/elbow_joint/i: 0.01
>  * /vel_based_pos_traj_controller/gains/elbow_joint/i_clamp: 1
>  * /vel_based_pos_traj_controller/gains/elbow_joint/p: 1.2
>  * /vel_based_pos_traj_controller/gains/shoulder_lift_joint/d: 0.1
>  * /vel_based_pos_traj_controller/gains/shoulder_lift_joint/i: 0.01
>  * /vel_based_pos_traj_controller/gains/shoulder_lift_joint/i_clamp: 1
>  * /vel_based_pos_traj_controller/gains/shoulder_lift_joint/p: 1.2
>  * /vel_based_pos_traj_controller/gains/shoulder_pan_joint/d: 0.1
>  * /vel_based_pos_traj_controller/gains/shoulder_pan_joint/i: 0.01
>  * /vel_based_pos_traj_controller/gains/shoulder_pan_joint/i_clamp: 1
>  * /vel_based_pos_traj_controller/gains/shoulder_pan_joint/p: 1.2
>  * /vel_based_pos_traj_controller/gains/wrist_1_joint/d: 0.1
>  * /vel_based_pos_traj_controller/gains/wrist_1_joint/i: 0.01
>  * /vel_based_pos_traj_controller/gains/wrist_1_joint/i_clamp: 1
>  * /vel_based_pos_traj_controller/gains/wrist_1_joint/p: 1.2
>  * /vel_based_pos_traj_controller/gains/wrist_2_joint/d: 0.1
>  * /vel_based_pos_traj_controller/gains/wrist_2_joint/i: 0.01
>  * /vel_based_pos_traj_controller/gains/wrist_2_joint/i_clamp: 1
>  * /vel_based_pos_traj_controller/gains/wrist_2_joint/p: 1.2
>  * /vel_based_pos_traj_controller/gains/wrist_3_joint/d: 0.1
>  * /vel_based_pos_traj_controller/gains/wrist_3_joint/i: 0.01
>  * /vel_based_pos_traj_controller/gains/wrist_3_joint/i_clamp: 1
>  * /vel_based_pos_traj_controller/gains/wrist_3_joint/p: 1.2
>  * /vel_based_pos_traj_controller/joints: ['shoulder_pan_jo...
>  * /vel_based_pos_traj_controller/state_publish_rate: 125
>  * /vel_based_pos_traj_controller/stop_trajectory_duration: 0.5
>  * /vel_based_pos_traj_controller/type: velocity_controll...
>  * /vel_based_pos_traj_controller/velocity_ff/elbow_joint: 1.0
>  * /vel_based_pos_traj_controller/velocity_ff/shoulder_lift_joint: 1.0
>  * /vel_based_pos_traj_controller/velocity_ff/shoulder_pan_joint: 1.0
>  * /vel_based_pos_traj_controller/velocity_ff/wrist_1_joint: 1.0
>  * /vel_based_pos_traj_controller/velocity_ff/wrist_2_joint: 1.0
>  * /vel_based_pos_traj_controller/velocity_ff/wrist_3_joint: 1.0
> 
> NODES
>   /
>     robot_state_publisher (robot_state_publisher/robot_state_publisher)
>     ros_control_controller_manager (controller_manager/controller_manager)
>     ros_control_controller_spawner (controller_manager/spawner)
>     ur_hardware_interface (ur_modern_driver/ur_driver)
> 
> auto-starting new master
> process[master]: started with pid [9896]
> ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to ed771b14-9207-11e9-bf24-54bf64a327d6
> process[rosout-1]: started with pid [9909]
> started core service [/rosout]
> process[ur_hardware_interface-2]: started with pid [9926]
> process[ros_control_controller_spawner-3]: started with pid [9927]
> process[ros_control_controller_manager-4]: started with pid [9928]
> process[robot_state_publisher-5]: started with pid [9937]
> [INFO] [1560889836.939756]: Controller Spawner: Waiting for service controller_manager/load_controller
> Loaded pos_based_pos_traj_controller
> Loaded joint_group_vel_controller
> [INFO] [1560889837.244148]: Controller Spawner: Waiting for service controller_manager/switch_controller
> [INFO] [1560889837.246657]: Controller Spawner: Waiting for service controller_manager/unload_controller
> [INFO] [1560889837.248709]: Loading controller: joint_state_controller
> [INFO] [1560889837.256904]: Loading controller: force_torque_sensor_controller
> [INFO] [1560889837.263650]: Loading controller: vel_based_pos_traj_controller
> [ros_control_controller_manager-4] process has finished cleanly
> log file: /home/e31098/.ros/log/ed771b14-9207-11e9-bf24-54bf64a327d6/ros_control_controller_manager-4*.log
> [INFO] [1560889837.556886]: Controller Spawner: Loaded controllers: joint_state_controller, force_torque_sensor_controller, vel_based_pos_traj_controller
> [INFO] [1560889837.587212]: Started controllers: joint_state_controller, force_torque_sensor_controller, vel_based_pos_traj_controller
> [ERROR] [1560889875.121085676]: Pipeline producer overflowed! <RTPacket>[ERROR] [1560889875.129009870]: Pipeline producer overflowed! <RTPacket>
[ERROR] [1560889875.1369
> 95574]: Pipeline producer overflowed! <RTPacket>
> [ERROR] [1560889875.145098228]: Pipeline producer overflowed! <RTPacket>
> [ERROR] [1560889875.153102114]: Pipeline producer overflowed! <RTPacket>
> [ERROR] [1560889875.161103043]: Pipeline producer overflowed! <RTPacket>
> [ERROR] [1560889875.169108359]: Pipeline producer overflowed! <RTPacket>
> [ERROR] [1560889875.177085054]: Pipeline producer overflowed! <RTPacket>
> [ERROR] [1560889875.185102811]: Pipeline producer overflowed! <RTPacket>

etc...

**Comment by gavanderhoorn** [comment] 2019-11-23 11:01
I'm closing this as we've officially deprecated this package.

Refer to the [announcement on ROS Discourse](https://discourse.ros.org/t/deprecation-of-ur-modern-driver/11629).

**Comment by gavanderhoorn** [comment] 2019-11-23 11:02
https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/6 seems like a similar issue in `ur_robot_driver` that should have been fixed in https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/18.

**Closed by gavanderhoorn** 2019-11-23 11:01 UTC
Labels: kinetic
