### ISSUE TITLE
Example code for publishing movej() movep() commands to the robot using /urscript topic

### ISSUE THREAD

**Issue by lakshmip001** [ros-industrial/ur_modern_driver#174] opened 2018-05-22 01:45 UTC
I need to sent a movep command using /urscript topic. I am new to using this ur_modern_driver .please provide an example code for publishing movep command on the topic.

**Comment by gonzalocasas** [comment] 2018-05-22 06:32
It's rather straightforward:

1. Start advertising on `/ur_driver/URScript` (using `std_msgs/String` message type)
2. Publish messages to it where the data payload is your URScript string, i.e. `movep(...)`
3. Party 🎆

**Comment by lakshmip001** [comment] 2018-05-23 03:00
Thanks . I will do.

**Comment by lakshmip001** [comment] 2018-05-23 03:05
Does it work only with real robot or can I work with the UR simulator?

**Comment by lakshmip001** [comment] 2018-05-23 09:26
Thanks gonzalocasas. I did write cpp code to publish movep() command on URScript topic . i can see publisher publishing data, when I do rostopic info. It shows a publisher: talker and subscriber: ur_driver. But I dont see robot movement. i added <exec_depend>ur_modern_driver<exec_depend>. suggest how I can move robot?

**Comment by gonzalocasas** [comment] 2018-05-25 07:16
@lakshmip001 please don't post duplicated issues. This is a duplicate of #175.

**Comment by gavanderhoorn** [comment] 2018-11-01 16:51
As this is a duplicate of #175 (and the original question seems to have been resolved), I'm closing this.

**Closed by gavanderhoorn** 2018-11-01 16:51 UTC
